### PR TITLE
Update .readthedocs.yaml

### PR DESCRIPTION
**Pull request by eirikurj**
## Purpose
Update `.readthedocs.yaml` file

## Expected time until merged
Few days

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Comment by akleb** [comment]
I am guessing that the issues are something to do with our updated formatting rules. I looked at the error output in the azure pipeline and I have no idea what the issue is. The error output doesn't make sense to me given what it is highlighting. 

Is there something wrong with the setup in this repo? I tried following the instructions for setting up flake8 on my own computer, but I am getting completely different errors than the ones showing up in the pipeline.

**Comment by marcomangano** [comment]
@akleb fixing it right now, no worries

**Comment by eirikurj** [comment]
The flake8 RST issues can be a little cryptic. As for setup, make sure you have the [extra requirements](https://github.com/mdolab/.github/blob/main/flake8-requirements.txt) installed and when running `flake8` in the command line, you need to point it to this [config file](https://github.com/mdolab/.github/blob/main/.flake8).

**Comment by marcomangano** [comment]
@akleb double check that the one-liners I added are consistent and useful (they are required by flake8)

**Comment by sseraj** [comment]
The required checks also need to be updated because the repo has been renamed.

**Comment by eirikurj** [comment]
Updated the checks, should be good to go now.

**Review by sseraj — APPROVED** [review]

**Pull request merged**
